### ISSUE TITLE
Internal Server Error when attempting to scan domain

### ISSUE THREAD

**Issue by benrfairless** [elmasy-com/columbus#1]
When attempting to run this command I get an “internal server error”

`curl -H "Accept: text/plain" "https://columbus.elmasy.com/api/lookup/wa.gov.au"`

**Comment by g0rbe** [comment]
Thanks for the issue!

`wa.gov.au` is a Top Level Domain, so the server should respond with 400 (Bad Request) instead of 500 (Internal Server Error).

To check the Top Level Domains, see: https://publicsuffix.org/list/public_suffix_list.dat

The server now respond:
```bash
$ curl -H "Accept: text/plain" "https://columbus.elmasy.com/api/lookup/wa.gov.au"
TLD only
```
