### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by albinowax** [elmasy-com/columbus#2]
Hi, thanks for the great tool! Unfortunately it's currently down - all the non-static pages are returning a 500 Internal Server Error:

https://columbus.elmasy.com/report/example.com
https://columbus.elmasy.com/statistics

**Comment by g0rbe** [comment]
Hi @albinowax !

Thanks for the report!
It was a chain of errors. My `mongosh` was good, the monitoring was good, but the actual servers are always failed and somehow i missed the GitHub notification about your issue.

Columbus should work now. Can you confirm?

**Comment by albinowax** [comment]
Looks fixed, many thanks!

**Comment by g0rbe** [comment]
@albinowax  Thanks for the sponsorship!
